export const planetsByGravitationalAcceleration = [
  {
    id: 'sun',
    name: 'Sun',
    gravitationalAcceleration: 274,
    description: 'The Sun is the star at the center of the Solar System. It is a nearly perfect sphere of hot plasma, heated to incandescence by nuclear fusion reactions in its core, radiating the energy mainly as light and infrared radiation. It is by far the most important source of energy for life on Earth. Its diameter is about 1.39 million kilometers, or 109 times that of Earth, and its mass is about 330,000 times that of Earth, accounting for about 99.86% of the total mass of the Solar System.',
    image: '/planets/sun.png',
    curiosities: [
      {
        name: 'mass',
        label: 'Mass',
        value: '1.989 × 10^30 kg',
        sublabel: 'The Sun is 333,000 times heavier than the Earth. It accounts for 99.86% of the total mass of the Solar System.',
      },
      {
        name: 'surface',
        label: 'Surface area',
        value: '6.09 × 10^12 km²',
        sublabel: 'The Sun is 11,990 times wider than the Earth.',
      },
      {
        name: 'volume',
        label: 'Volume',
        value: '1.41 × 10^18 km³',
      },
      {
        name: 'radius',
        label: 'Radius',
        value: '695,700 km',
        sublabel: 'The Sun is 109 times wider than the Earth. So you could fit 1.3 million Earths inside the Sun.',
      },
      {
        name: 'distance',
        label: 'Distance from Earth',
        value: '149.6 million km',
        sublabel: 'It takes 8 minutes and 19 seconds for sunlight to travel from the Sun’s surface to the Earth.',
      },
      {
        name: 'age',
        label: 'Age',
        value: '4.603 billion years',
        sublabel: 'The Sun is middle-aged and will remain in its current state for approximately another 4.5 billion years.',
      },
      {
        name: 'temperature',
        label: 'Surface temperature',
        value: '5,500 °C',
        sublabel: 'You could boil 100 billion kettles of water with the energy that reaches the Earth from the Sun each second.',
      },
      {
        name: 'daytime',
        label: 'Daytime',
        value: '25 days',
        sublabel: 'The Sun rotates on its axis once every 25 days.',
      }
    ],
  },
  {
    id: 'mercury',
    name: 'Mercury',
    description: 'Mercury is the smallest and innermost planet in the Solar System. Its orbit around the Sun takes 87.97 Earth days, the shortest of all the planets in the Solar System. It is named after the Roman deity Mercury, the messenger of the gods.',
    gravitationalAcceleration: 3.7,
    image: '/planets/mercury.png',
    curiosities: [
      {
        name: 'mass',
        label: 'Mass',
        value: '3.285 × 10^23 kg',
        sublabel: 'Mercury is 5.5% the mass of the Earth.',
      },
      {
        name: 'surface',
        label: 'Surface area',
        value: '7.48 × 10^7 km²',
        sublabel: 'Mercury is 28% the surface area of the Earth.',
      },
      {
        name: 'volume',
        label: 'Volume',
        value: '6.083 × 10^10 km³',
        sublabel: 'Mercury is 5.4% the volume of the Earth.',
      },
      {
        name: 'radius',
        label: 'Radius',
        value: '2,439.7 km',
        sublabel: 'Mercury is 38% the radius of the Earth.',
      },
      {
        name: 'distance',
        label: 'Distance from Sun',
        value: '57.9 million km',
        sublabel: 'Mercury is 0.39 times the distance of the Earth from the Sun.',
      },
      {
        name: 'distance',
        label: 'Distance from Earth',
        value: '77.3 million km',
        sublabel: 'Mercury is 0.52 times the distance of the Earth from the Sun.',
      },
      {
        name: 'age',
        label: 'Age',
        value: '4.503 billion years',
        sublabel: 'Mercury is 0.97 times the age of the Earth.',
      },
      {
        name: 'temperature',
        label: 'Surface temperature',
        value: '430 °C',
        sublabel: 'Mercury is 0.73 times the temperature of the Earth.',
      },
      {
        name: 'daytime',
        label: 'Daytime',
        value: '58 days',
        sublabel: 'Mercury is 2.4 times the daytime of the Earth.',
      }
    ],
  },
  {
    id: 'venus',
    name: 'Venus',
    description: 'Venus is the second planet from the Sun. It is named after the Roman goddess of love and beauty. As the brightest natural object in Earth\'s night sky after the Moon, Venus can cast shadows and can be, on rare occasion, visible to the naked eye in broad daylight.',
    gravitationalAcceleration: 8.87,
    image: '/planets/venus.png',
    curiosities: [
      {
        name: 'mass',
        label: 'Mass',
        value: '4.867 × 10^24 kg',
        sublabel: 'Venus is 81.5% the mass of the Earth.',
      },
      {
        name: 'surface',
        label: 'Surface area',
        value: '4.60 × 10^8 km²',
        sublabel: 'Venus is 90% the surface area of the Earth.',
      },
      {
        name: 'volume',
        label: 'Volume',
        value: '9.38 × 10^11 km³',
        sublabel: 'Venus is 86% the volume of the Earth.',
      },
      {
        name: 'radius',
        label: 'Radius',
        value: '6,051.8 km',
        sublabel: 'Venus is 95% the radius of the Earth.',
      },
      {
        name: 'distance',
        label: 'Distance from Sun',
        value: '108.2 million km',
        sublabel: 'Venus is 0.73 times the distance of the Earth from the Sun.',
      },
      {
        name: 'distance',
        label: 'Distance from Earth',
        value: '38.2 million km',
        sublabel: 'Venus is 0.27 times the distance of the Earth from the Sun.',
      },
      {
        name: 'age',
        label: 'Age',
        value: '4.503 billion years',
        sublabel: 'Venus is 0.97 times the age of the Earth.',
      },
      {
        name: 'temperature',
        label: 'Surface temperature',
        value: '471 °C',
        sublabel: 'Venus is 1.18 times the temperature of the Earth.',
      },
      {
        name: 'daytime',
        label: 'Daytime',
        value: '116 days',
        sublabel: 'Venus is 4.8 times the daytime of the Earth.',
      }
    ],
  },
  {
    id: 'earth',
    name: 'Earth',
    description: 'Earth is the third planet from the Sun and the only astronomical object known to harbor life. About 29% of Earth\'s surface is land consisting of continents and islands. The remaining 71% is covered with water, mostly by oceans but also by lakes, rivers and other fresh water, which together constitute the hydrosphere. Much of Earth\'s polar regions are covered in ice. Earth\'s outer layer is divided into several rigid tectonic plates that migrate across the surface over many millions of years. Earth\'s interior remains active with a solid iron inner core, a liquid outer core that generates Earth\'s magnetic field, and a convecting mantle that drives plate tectonics.',
    gravitationalAcceleration: 9.81,
    image: '/planets/earth.png',
    curiosities: [
      {
        name: 'mass',
        label: 'Mass',
        value: '5.972 × 10^24 kg',
        sublabel: 'The Earth is 5.5% the mass of the Sun.',
      },
      {
        name: 'surface',
        label: 'Surface area',
        value: '5.10 × 10^8 km²',
        sublabel: 'The Earth is 0.83% the surface area of the Sun.',
      },
      {
        name: 'volume',
        label: 'Volume',
        value: '1.083 × 10^12 km³',
        sublabel: 'The Earth is 0.77% the volume of the Sun.',
      },
      {
        name: 'radius',
        label: 'Radius',
        value: '6,371 km',
        sublabel: 'The Earth is 0.09% the radius of the Sun.',
      },
      {
        name: 'distance',
        label: 'Distance from Sun',
        value: '149.6 million km',
        sublabel: 'The Earth is 1.00 times the distance of the Sun from the Earth.',
      },
      {
        name: 'distance',
        label: 'Distance from Earth',
        value: '0 km',
        sublabel: 'The Earth is 0.00 times the distance of the Sun from the Earth.',
      },
      {
        name: 'age',
        label: 'Age',
        value: '4.503 billion years',
        sublabel: 'The Earth is 1.00 times the age of the Sun.',
      },
      {
        name: 'temperature',
        label: 'Surface temperature',
        value: '15 °C',
        sublabel: 'The Earth is 0.00 times the temperature of the Sun.',
      },
      {
        name: 'daytime',
        label: 'Daytime',
        value: '24 hours',
        sublabel: 'The Earth is 0.00 times the daytime of the Sun.',
      }
    ],
  },
  {
    id: 'moon',
    name: 'Moon',
    description: 'The Moon is an astronomical body orbiting Earth as its only natural satellite. It is the fifth-largest satellite in the Solar System, and by far the largest among planetary satellites relative to the size of the planet that it orbits. The Moon is, after Jupiter\'s satellite Io, the second-densest satellite in the Solar System among those whose densities are known.',
    gravitationalAcceleration: 1.62,
    image: '/planets/moon.png',
    curiosities: [
      {
        name: 'mass',
        label: 'Mass',
        value: '7.347 × 10^22 kg',
        sublabel: 'The Moon is 1.23% the mass of the Earth.',
      },
      {
        name: 'surface',
        label: 'Surface area',
        value: '3.79 × 10^7 km²',
        sublabel: 'The Moon is 7.35% the surface area of the Earth.',
      },
      {
        name: 'volume',
        label: 'Volume',
        value: '2.195 × 10^10 km³',
        sublabel: 'The Moon is 2.03% the volume of the Earth.',
      },
      {
        name: 'radius',
        label: 'Radius',
        value: '1,737.1 km',
        sublabel: 'The Moon is 27% the radius of the Earth.',
      },
      {
        name: 'distance',
        label: 'Distance from Sun',
        value: '149.6 million km',
        sublabel: 'The Moon is 1.00 times the distance of the Earth from the Sun.',
      },
      {
        name: 'distance',
        label: 'Distance from Earth',
        value: '384,400 km',
        sublabel: 'The Moon is 1.00 times the distance of the Earth from the Sun.',
      },
      {
        name: 'age',
        label: 'Age',
        value: '4.503 billion years',
        sublabel: 'The Moon is 1.00 times the age of the Earth.',
      },
      {
        name: 'temperature',
        label: 'Surface temperature',
        value: '-233 to 123 °C',
        sublabel: 'The Moon is 0.00 times the temperature of the Earth.',
      },
      {
        name: 'daytime',
        label: 'Daytime',
        value: '27 days',
        sublabel: 'The Moon is 1.1 times the daytime of the Earth.',
      }
    ],
  },
  {
    id: 'mars',
    name: 'Mars',
    description: 'Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System, being larger than only Mercury. In English, Mars carries the name of the Roman god of war and is often referred to as the "Red Planet". The latter refers to the effect of the iron oxide prevalent on Mars\'s surface, which gives it a reddish appearance distinctive among the astronomical bodies visible to the naked eye.',
    gravitationalAcceleration: 3.711,
    image: '/planets/mars.png',
    curiosities: [
      {
        name: 'mass',
        label: 'Mass',
        value: '6.39 × 10^23 kg',
        sublabel: 'Mars is 10.7% the mass of the Earth.',
      },
      {
        name: 'surface',
        label: 'Surface area',
        value: '1.45 × 10^8 km²',
        sublabel: 'Mars is 28% the surface area of the Earth.',
      },
      {
        name: 'volume',
        label: 'Volume',
        value: '1.631 × 10^11 km³',
        sublabel: 'Mars is 14.9% the volume of the Earth.',
      },
      {
        name: 'radius',
        label: 'Radius',
        value: '3,389.5 km',
        sublabel: 'Mars is 53% the radius of the Earth.',
      },
      {
        name: 'distance',
        label: 'Distance from Sun',
        value: '227.9 million km',
        sublabel: 'Mars is 1.52 times the distance of the Earth from the Sun.',
      },
      {
        name: 'distance',
        label: 'Distance from Earth',
        value: '78.3 million km',
        sublabel: 'Mars is 0.53 times the distance of the Earth from the Sun.',
      },
      {
        name: 'age',
        label: 'Age',
        value: '4.503 billion years',
        sublabel: 'Mars is 0.97 times the age of the Earth.',
      },
      {
        name: 'temperature',
        label: 'Surface temperature',
        value: '-87 to -5 °C',
        sublabel: 'Mars is 0.58 times the temperature of the Earth.',
      },
      {
        name: 'daytime',
        label: 'Daytime',
        value: '24 hours',
        sublabel: 'Mars is 1.0 times the daytime of the Earth.',
      }
    ],
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    description: 'Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass one-thousandth that of the Sun, but two-and-a-half times that of all the other planets in the Solar System combined. Jupiter is one of the brightest objects visible to the naked eye in the night sky, and has been known to ancient civilizations since before recorded history.',
    gravitationalAcceleration: 24.79,
    image: '/planets/jupiter.png',
    curiosities: [
      {
        name: 'mass',
        label: 'Mass',
        value: '1.898 × 10^27 kg',
        sublabel: 'Jupiter is 318 times the mass of the Earth.',
      },
      {
        name: 'surface',
        label: 'Surface area',
        value: '6.1419 × 10^10 km²',
        sublabel: 'Jupiter is 122 times the surface area of the Earth.',
      },
      {
        name: 'volume',
        label: 'Volume',
        value: '1.431 × 10^15 km³',
        sublabel: 'Jupiter is 1,321 times the volume of the Earth.',
      },
      {
        name: 'radius',
        label: 'Radius',
        value: '69,911 km',
        sublabel: 'Jupiter is 11 times the radius of the Earth.',
      },
      {
        name: 'distance',
        label: 'Distance from Sun',
        value: '778.5 million km',
        sublabel: 'Jupiter is 5.20 times the distance of the Earth from the Sun.',
      },
      {
        name: 'distance',
        label: 'Distance from Earth',
        value: '628.7 million km',
        sublabel: 'Jupiter is 4.22 times the distance of the Earth from the Sun.',
      },
      {
        name: 'age',
        label: 'Age',
        value: '4.503 billion years',
        sublabel: 'Jupiter is 0.97 times the age of the Earth.',
      },
      {
        name: 'temperature',
        label: 'Surface temperature',
        value: '-108 °C',
        sublabel: 'Jupiter is 0.72 times the temperature of the Earth.',
      },
      {
        name: 'daytime',
        label: 'Daytime',
        value: '10 hours',
        sublabel: 'Jupiter is 0.42 times the daytime of the Earth.',
      }
    ],
  },
  {
    id: 'saturn',
    name: 'Saturn',
    description: 'Saturn is the sixth planet from the Sun and the second-largest in the Solar System, after Jupiter. It is a gas giant with an average radius of about nine times that of Earth. It only has one-eighth the average density of Earth; however, with its larger volume, Saturn is over 95 times more massive.',
    gravitationalAcceleration: 10.44,
    image: '/planets/saturn.png',
    curiosities: [
      {
        name: 'mass',
        label: 'Mass',
        value: '5.683 × 10^26 kg',
        sublabel: 'Saturn is 95.2 times the mass of the Earth.',
      },
      {
        name: 'surface',
        label: 'Surface area',
        value: '4.27 × 10^10 km²',
        sublabel: 'Saturn is 84.8 times the surface area of the Earth.',
      },
      {
        name: 'volume',
        label: 'Volume',
        value: '8.2713 × 10^14 km³',
        sublabel: 'Saturn is 763 times the volume of the Earth.',
      },
      {
        name: 'radius',
        label: 'Radius',
        value: '58,232 km',
        sublabel: 'Saturn is 9.13 times the radius of the Earth.',
      },
      {
        name: 'distance',
        label: 'Distance from Sun',
        value: '1.43 billion km',
        sublabel: 'Saturn is 9.58 times the distance of the Earth from the Sun.',
      },
      {
        name: 'distance',
        label: 'Distance from Earth',
        value: '1.34 billion km',
        sublabel: 'Saturn is 9.00 times the distance of the Earth from the Sun.',
      },
      {
        name: 'age',
        label: 'Age',
        value: '4.503 billion years',
        sublabel: 'Saturn is 0.97 times the age of the Earth.',
      },
      {
        name: 'temperature',
        label: 'Surface temperature',
        value: '-139 °C',
        sublabel: 'Saturn is 0.93 times the temperature of the Earth.',
      },
      {
        name: 'daytime',
        label: 'Daytime',
        value: '10 hours',
        sublabel: 'Saturn is 0.42 times the daytime of the Earth.',
      }
    ],
  },
  {
    id: 'uranus',
    name: 'Uranus',
    description: 'Uranus is the seventh planet from the Sun. Its name is a reference to the Greek god of the sky, Uranus, who, according to Greek mythology, was the grandfather of Zeus and father of Cronus. It has the third-largest planetary radius and fourth-largest planetary mass in the Solar System.',
    gravitationalAcceleration: 8.87,
    image: '/planets/uranus.png',
    curiosities: [
      {
        name: 'mass',
        label: 'Mass',
        value: '8.681 × 10^25 kg',
        sublabel: 'Uranus is 14.5 times the mass of the Earth.',
      },
      {
        name: 'surface',
        label: 'Surface area',
        value: '8.1156 × 10^9 km²',
        sublabel: 'Uranus is 16.1 times the surface area of the Earth.',
      },
      {
        name: 'volume',
        label: 'Volume',
        value: '6.833 × 10^13 km³',
        sublabel: 'Uranus is 63.1 times the volume of the Earth.',
      },
      {
        name: 'radius',
        label: 'Radius',
        value: '25,362 km',
        sublabel: 'Uranus is 3.98 times the radius of the Earth.',
      },
      {
        name: 'distance',
        label: 'Distance from Sun',
        value: '2.87 billion km',
        sublabel: 'Uranus is 19.2 times the distance of the Earth from the Sun.',
      },
      {
        name: 'distance',
        label: 'Distance from Earth',
        value: '2.77 billion km',
        sublabel: 'Uranus is 18.6 times the distance of the Earth from the Sun.',
      },
      {
        name: 'age',
        label: 'Age',
        value: '4.503 billion years',
        sublabel: 'Uranus is 0.97 times the age of the Earth.',
      },
      {
        name: 'temperature',
        label: 'Surface temperature',
        value: '-197 °C',
        sublabel: 'Uranus is 1.32 times the temperature of the Earth.',
      },
      {
        name: 'daytime',
        label: 'Daytime',
        value: '17 hours',
        sublabel: 'Uranus is 0.71 times the daytime of the Earth.',
      }
    ],
  },
  {
    id: 'neptune',
    name: 'Neptune',
    description: 'Neptune is the eighth and farthest-known Solar planet from the Sun. In the Solar System, it is the fourth-largest planet by diameter, the third-most-massive planet, and the densest giant planet. It is 17 times the mass of Earth, slightly more massive than its near-twin Uranus.',
    gravitationalAcceleration: 11.15,
    image: '/planets/neptune.png',
    curiosities: [
      {
        name: 'mass',
        label: 'Mass',
        value: '1.024 × 10^26 kg',
        sublabel: 'Neptune is 17.1 times the mass of the Earth.',
      },
      {
        name: 'surface',
        label: 'Surface area',
        value: '7.618 × 10^9 km²',
        sublabel: 'Neptune is 15.1 times the surface area of the Earth.',
      },
      {
        name: 'volume',
        label: 'Volume',
        value: '6.254 × 10^13 km³',
        sublabel: 'Neptune is 57.7 times the volume of the Earth.',
      },
      {
        name: 'radius',
        label: 'Radius',
        value: '24,622 km',
        sublabel: 'Neptune is 3.86 times the radius of the Earth.',
      },
      {
        name: 'distance',
        label: 'Distance from Sun',
        value: '4.50 billion km',
        sublabel: 'Neptune is 30.1 times the distance of the Earth from the Sun.',
      },
      {
        name: 'distance',
        label: 'Distance from Earth',
        value: '4.40 billion km',
        sublabel: 'Neptune is 29.5 times the distance of the Earth from the Sun.',
      },
      {
        name: 'age',
        label: 'Age',
        value: '4.503 billion years',
        sublabel: 'Neptune is 0.97 times the age of the Earth.',
      },
      {
        name: 'temperature',
        label: 'Surface temperature',
        value: '-201 °C',
        sublabel: 'Neptune is 1.35 times the temperature of the Earth.',
      },
      {
        name: 'daytime',
        label: 'Daytime',
        value: '16 hours',
        sublabel: 'Neptune is 0.67 times the daytime of the Earth.',
      }
    ],
  },
  {
    id: 'pluto',
    name: 'Pluto',
    description: 'Pluto is an icy dwarf planet in the Kuiper belt, a ring of bodies beyond the orbit of Neptune. It was the first and the largest Kuiper belt object to be discovered. Pluto was discovered by Clyde Tombaugh in 1930 and declared to be the ninth planet from the Sun. After 1992, its status as a planet was questioned following the discovery of several objects of similar size in the Kuiper belt. In 2005, Eris, a dwarf planet in the scattered disc which is 27% more massive than Pluto, was discovered. This led the International Astronomical Union (IAU) to define the term "planet" formally in 2006, during their 26th General Assembly. That definition excluded Pluto and reclassified it as a dwarf planet.',
    gravitationalAcceleration: 0.62,
    image: '/planets/pluto.png',
    curiosities: [
      {
        name: 'mass',
        label: 'Mass',
        value: '1.30900 × 10^22 kg',
        sublabel: 'Pluto is 0.22% the mass of the Earth.',
      },
      {
        name: 'surface',
        label: 'Surface area',
        value: '1.779 × 10^7 km²',
        sublabel: 'Pluto is 0.03% the surface area of the Earth.',
      },
      {
        name: 'volume',
        label: 'Volume',
        value: '6.39 × 10^9 km³',
        sublabel: 'Pluto is 0.0059% the volume of the Earth.',
      },
      {
        name: 'radius',
        label: 'Radius',
        value: '1,188.3 km',
        sublabel: 'Pluto is 0.18% the radius of the Earth.',
      },
      {
        name: 'distance',
        label: 'Distance from Sun',
        value: '5.91 billion km',
        sublabel: 'Pluto is 39.5 times the distance of the Earth from the Sun.',
      },
      {
        name: 'distance',
        label: 'Distance from Earth',
        value: '5.81 billion km',
        sublabel: 'Pluto is 39.0 times the distance of the Earth from the Sun.',
      },
      {
        name: 'age',
        label: 'Age',
        value: '4.503 billion years',
        sublabel: 'Pluto is 0.97 times the age of the Earth.',
      },
      {
        name: 'temperature',
        label: 'Surface temperature',
        value: '-229 °C',
        sublabel: 'Pluto is 0.00 times the temperature of the Earth.',
      },
      {
        name: 'daytime',
        label: 'Daytime',
        value: '153 hours',
        sublabel: 'Pluto is 6.4 times the daytime of the Earth.',
      }
    ],
  },
];